[dock]
apps = [
  "/System/Applications/Apps.app",
  "/Applications/Firefox.app",
  "/Applications/Slack.app",
  "/Applications/Visual Studio Code.app",
  "/Applications/Ghostty.app",
  "/Applications/Sublime Text.app",
  "/Applications/Spotify.app",
]
folders = []
