[icons]
"/Applications/Steam.app" = "steam.icns"
"$HOME/Applications/Stardew Valley.app" = "stardew_valley.icns"
"$HOME/DPG" = "dpg_media.icns"
"/Applications/NoSQL Workbench.app" = "nosql_workbench.icns"
